use anchor_lang::prelude::*;

// This is your program's public key and it will update
// automatically when you build the project.
use anchor_lang::prelude::*;

/// Program ID will be auto-generated by Anchor when deploying
declare_id!("4118MKuzhYvbNYmQjA9rkqveT5V2ksyo1tNRH3zrqXpo");

#[program]
pub mod simple_escrow {
    use super::*;

    /// Buyer initializes escrow by depositing funds
    pub fn initialize_escrow(
        ctx: Context<InitializeEscrow>,
        amount: u64,
    ) -> Result<()> {
        let escrow = &mut ctx.accounts.escrow_account;
        escrow.buyer = *ctx.accounts.buyer.key;
        escrow.seller = *ctx.accounts.seller.key;
        escrow.amount = amount;
        escrow.state = EscrowState::Funded;

        // Transfer funds from buyer to escrow vault
        let ix = anchor_lang::solana_program::system_instruction::transfer(
            &ctx.accounts.buyer.key(),
            &ctx.accounts.vault.key(),
            amount,
        );
        anchor_lang::solana_program::program::invoke(
            &ix,
            &[
                ctx.accounts.buyer.to_account_info(),
                ctx.accounts.vault.to_account_info(),
                ctx.accounts.system_program.to_account_info(),
            ],
        )?;

        Ok(())
    }

    /// Buyer approves release, allowing seller to claim
    pub fn approve(ctx: Context<Approve>) -> Result<()> {
        let escrow = &mut ctx.accounts.escrow_account;
        require!(
            escrow.state == EscrowState::Funded,
            EscrowError::InvalidState
        );
        require!(
            escrow.buyer == *ctx.accounts.buyer.key,
            EscrowError::NotAuthorized
        );

        escrow.state = EscrowState::Approved;
        Ok(())
    }

    /// Seller claims funds after approval
    pub fn claim(ctx: Context<Claim>) -> Result<()> {
        let escrow = &mut ctx.accounts.escrow_account;
        require!(
            escrow.state == EscrowState::Approved,
            EscrowError::InvalidState
        );
        require!(
            escrow.seller == *ctx.accounts.seller.key,
            EscrowError::NotAuthorized
        );

        // Transfer funds from vault to seller
        **ctx.accounts.vault.to_account_info().try_borrow_mut_lamports()? -= escrow.amount;
        **ctx.accounts.seller.to_account_info().try_borrow_mut_lamports()? += escrow.amount;

        escrow.state = EscrowState::Released;
        Ok(())
    }

    /// Buyer cancels escrow before seller claims
    pub fn cancel(ctx: Context<Cancel>) -> Result<()> {
        let escrow = &mut ctx.accounts.escrow_account;
        require!(
            escrow.state == EscrowState::Funded,
            EscrowError::InvalidState
        );
        require!(
            escrow.buyer == *ctx.accounts.buyer.key,
            EscrowError::NotAuthorized
        );

        // Refund buyer
        **ctx.accounts.vault.to_account_info().try_borrow_mut_lamports()? -= escrow.amount;
        **ctx.accounts.buyer.to_account_info().try_borrow_mut_lamports()? += escrow.amount;

        escrow.state = EscrowState::Cancelled;
        Ok(())
    }
}

/// Escrow account storing state
#[account]
pub struct EscrowAccount {
    pub buyer: Pubkey,
    pub seller: Pubkey,
    pub amount: u64,
    pub state: EscrowState,
}

/// Escrow states
#[derive(AnchorSerialize, AnchorDeserialize, Clone, PartialEq, Eq)]
pub enum EscrowState {
    Funded,
    Approved,
    Released,
    Cancelled,
}

/// Custom errors
#[error_code]
pub enum EscrowError {
    #[msg("Caller not authorized for this action")]
    NotAuthorized,
    #[msg("Invalid state for this action")]
    InvalidState,
}

/// Contexts for instructions
#[derive(Accounts)]
pub struct InitializeEscrow<'info> {
    #[account(mut)]
    pub buyer: Signer<'info>,
    /// CHECK: Seller is just a pubkey
    pub seller: UncheckedAccount<'info>,
    #[account(init, payer = buyer, space = 8 + 32 + 32 + 8 + 1)]
    pub escrow_account: Account<'info, EscrowAccount>,
    #[account(mut)]
    pub vault: SystemAccount<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct Approve<'info> {
    #[account(mut)]
    pub buyer: Signer<'info>,
    #[account(mut)]
    pub escrow_account: Account<'info, EscrowAccount>,
}

#[derive(Accounts)]
pub struct Claim<'info> {
    #[account(mut)]
    pub seller: Signer<'info>,
    #[account(mut)]
    pub escrow_account: Account<'info, EscrowAccount>,
    #[account(mut)]
    pub vault: SystemAccount<'info>,
}

#[derive(Accounts)]
pub struct Cancel<'info> {
    #[account(mut)]
    pub buyer: Signer<'info>,
    #[account(mut)]
    pub escrow_account: Account<'info, EscrowAccount>,
    #[account(mut)]
    pub vault: SystemAccount<'info>,
}